# Conditional Filtering

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/Car_sales.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
# Find car details whose model year is 2017.
filter_car = df['year'] == 2017
df[filter_car]
# or
'''
df[df['year]==2017]
'''

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
16,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
22,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
54,Maruti Swift Dzire VDI Optional,2017,725000,18500,Diesel,Dealer,Manual,First Owner
...,...,...,...,...,...,...,...,...
4264,Hyundai i20 1.4 Sportz,2017,680000,44000,Diesel,Dealer,Manual,First Owner
4273,Maruti Ertiga SHVS VDI,2017,890000,60000,Diesel,Individual,Manual,Second Owner
4309,Datsun GO Plus T,2017,350000,10171,Petrol,Dealer,Manual,First Owner
4311,Toyota Camry Hybrid 2.5,2017,1900000,20118,Petrol,Dealer,Automatic,First Owner
4315,Maruti Celerio ZXI,2017,415000,20000,Petrol,Individual,Manual,First Owner

In [8]:
# now to select only specific col let here be name year selling price where model year is 2017.
df[df['year']==2017][['name','year','selling_price']]
# or
# df[filter_car][['name','year','selling_price']]

                                 name  year  selling_price
3              Datsun RediGO T Option  2017         250000
9            Maruti Celerio Green VXI  2017         365000
16             Datsun RediGO T Option  2017         250000
22           Maruti Celerio Green VXI  2017         365000
54    Maruti Swift Dzire VDI Optional  2017         725000
...                               ...   ...            ...
4264           Hyundai i20 1.4 Sportz  2017         680000
4273           Maruti Ertiga SHVS VDI  2017         890000
4309                 Datsun GO Plus T  2017         350000
4311          Toyota Camry Hybrid 2.5  2017        1900000
4315               Maruti Celerio ZXI  2017         415000

[466 rows x 3 columns]

In [ ]:
# Find car details whose price is in range of 300000 to 600000.
# for continuous data like price, salary, temperature
# in such data which has range we have to use either and ,or between(not or).
# here in pandas and is denoted by &.
# using and(&)
car_price = df[(df['selling_price'] >= 300000) & (df['selling_price']<=600000)]
car_price

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4322,Hyundai Verna 1.6 SX CRDi (O),2013,500000,120000,Diesel,Individual,Manual,First Owner
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,530000,175000,Diesel,Individual,Manual,Third Owner
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner

In [12]:
# using between
car_price_between=df[df['selling_price'].between(300000,600000)]
car_price_between

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4322,Hyundai Verna 1.6 SX CRDi (O),2013,500000,120000,Diesel,Individual,Manual,First Owner
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,530000,175000,Diesel,Individual,Manual,Third Owner
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner

In [ ]:
# in large dataset & work faster as & works fully in boolean but between first compares values and converts to boolean
# in query optimization must useand(&).
# in between both values are inclusive.

In [ ]:
# for categorical data we must use or(not and), or in(.isin())

In [ ]:
# to find unique values
df['fuel'].unique() #to get names of unique values

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [14]:
# to find number of unique values.
df['fuel'].nunique()

5

In [ ]:
# Find cars whose emission fuel type is Petrol or CNG.
car_fuel=df[(df['fuel']=='Petrol')|(df['fuel']=='CNG')]
car_fuel
# here \is CNG

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [16]:
car_fuel_in = df[df['fuel'].isin(['Petrol','CNG'])]
car_fuel_in

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [18]:
unique_fuel=car_fuel['fuel'].unique()
unique_fuel

array(['Petrol', 'CNG'], dtype=object)

In [22]:
# Find car details whose transmission mode is Automatic, fuel type is Petrol/Electric and which is driven for around 20000 to 35000.
car_details = df[(df['transmission']=='Automatic')
                 & ((df['fuel']=='Petrol') | (df['fuel']=='Electric')) & 
                 ((df['km_driven']>=20000) & (df['km_driven']<=35000))]
car_details

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
12,Toyota Corolla Altis 1.8 VL CVT,2018,1650000,25000,Petrol,Dealer,Automatic,First Owner
25,Toyota Corolla Altis 1.8 VL CVT,2018,1650000,25000,Petrol,Dealer,Automatic,First Owner
357,Maruti Alto K10 VXI AGS Optional,2018,300000,25000,Petrol,Individual,Automatic,First Owner
453,Maruti Wagon R AMT VXI,2018,420000,24000,Petrol,Individual,Automatic,First Owner
543,Volkswagen Polo GTI,2017,850000,20000,Petrol,Dealer,Automatic,Second Owner
710,Maruti Celerio VXI AT,2017,415000,32670,Petrol,Dealer,Automatic,First Owner
745,Hyundai Grand i10 AT Asta,2015,400000,30000,Petrol,Individual,Automatic,First Owner
806,Maruti Wagon R AMT VXI,2014,300000,28942,Petrol,Dealer,Automatic,First Owner
969,Toyota Camry 2.5 Hybrid,2017,1900000,20000,Petrol,Individual,Automatic,First Owner
1024,Honda City i-VTEC CVT ZX,2018,1140000,23038,Petrol,Trustmark Dealer,Automatic,First Owner
1065,Audi A4 30 TFSI Technology,2018,3100000,22000,Petrol,Individual,Automatic,First Owner
1148,Honda Amaze V CVT Petrol BSIV,2018,725000,26000,Petrol,Dealer,Automatic,First Owner
1219,Maruti Baleno Delta Automatic,2018,550000,25000,Petrol,Individual,Automatic,First Owner
1273,Maruti Celerio VXI AT,2015,395000,30500,Petrol,Dealer,Automatic,Second Owner
1280,Honda Jazz VX CVT,2016,580000,32000,Petrol,Dealer,Automatic,First Owner
1351,Renault KWID Climber 1.0 AMT,2017,300000,20000,Petrol,Individual,Automatic,First Owner
1407,Hyundai Grand i10 1.2 Kappa Magna AT,2019,650000,20000,Petrol,Individual,Automatic,First Owner
1408,Maruti Ertiga BSIV VXI AT,2017,800000,30600,Petrol,Individual,Automatic,First Owner
1745,Maruti Alto K10 VXI AGS,2017,375000,27289,Petrol,Dealer,Automatic,First Owner
2044,Mercedes-Benz E-Class 230,1998,1000000,35000,Petrol,Individual,Automatic,Second Owner
2068,Maruti Wagon R AX,2012,300000,30000,Petrol,Individual,Automatic,Second Owner
2182,Volkswagen Polo GTI,2017,850000,20000,Petrol,Dealer,Automatic,Second Owner
2299,Toyota Camry Hybrid 2.5,2017,1900000,20118,Petrol,Dealer,Automatic,First Owner
2323,Audi A4 30 TFSI Technology,2018,3100000,22000,Petrol,Individual,Automatic,First Owner
2337,Mercedes-Benz E-Class 230,1998,1000000,35000,Petrol,Individual,Automatic,Second Owner
2404,Honda City i-VTEC CVT ZX,2018,1225000,22000,Petrol,Dealer,Automatic,First Owner
2461,Maruti Wagon R AMT VXI,2014,300000,28942,Petrol,Dealer,Automatic,First Owner
2531,Maruti Alto K10 VXI AGS,2017,375000,27289,Petrol,Dealer,Automatic,First Owner
2859,Maruti Celerio ZXI AT,2017,509999,25000,Petrol,Individual,Automatic,First Owner
3045,Maruti Swift AMT VXI,2019,575000,25000,Petrol,Individual,Automatic,First Owner
3157,Maruti Wagon R AMT VXI,2014,300000,28942,Petrol,Dealer,Automatic,First Owner
3356,Hyundai Elite i20 Asta Option CVT BSIV,2017,635000,25000,Petrol,Dealer,Automatic,First Owner
3537,Maruti Ignis 1.2 AMT Alpha BSIV,2018,700000,25000,Petrol,Individual,Automatic,First Owner
3655,Maruti Baleno Zeta Automatic,2018,700000,26000,Petrol,Individual,Automatic,First Owner
3730,Hyundai Grand i10 1.2 Kappa Sportz AT,2018,550000,35000,Petrol,Individual,Automatic,First Owner
3846,Datsun RediGO AMT 1.0 S,2018,300000,25000,Petrol,Individual,Automatic,First Owner
3860,Hyundai Creta 1.6 SX Automatic,2017,1035000,23000,Petrol,Dealer,Automatic,First Owner
3892,Volkswagen Polo GT 1.0 TSI,2019,950000,24000,Petrol,Individual,Automatic,First Owner
4119,Honda Amaze V CVT Petrol BSIV,2018,725000,26000,Petrol,Dealer,Automatic,First Owner
4311,Toyota Camry Hybrid 2.5,2017,1900000,20118,Petrol,Dealer,Automatic,First Owner

In [25]:
# to get only specific col
car_details[['name','selling_price']]

                                        name  selling_price
12           Toyota Corolla Altis 1.8 VL CVT        1650000
25           Toyota Corolla Altis 1.8 VL CVT        1650000
357         Maruti Alto K10 VXI AGS Optional         300000
453                   Maruti Wagon R AMT VXI         420000
543                      Volkswagen Polo GTI         850000
710                    Maruti Celerio VXI AT         415000
745                Hyundai Grand i10 AT Asta         400000
806                   Maruti Wagon R AMT VXI         300000
969                  Toyota Camry 2.5 Hybrid        1900000
1024                Honda City i-VTEC CVT ZX        1140000
1065              Audi A4 30 TFSI Technology        3100000
1148           Honda Amaze V CVT Petrol BSIV         725000
1219           Maruti Baleno Delta Automatic         550000
1273                   Maruti Celerio VXI AT         395000
1280                       Honda Jazz VX CVT         580000
1351            Renault KWID Climber 1.0 AMT         300000
1407    Hyundai Grand i10 1.2 Kappa Magna AT         650000
1408               Maruti Ertiga BSIV VXI AT         800000
1745                 Maruti Alto K10 VXI AGS         375000
2044               Mercedes-Benz E-Class 230        1000000
2068                       Maruti Wagon R AX         300000
2182                     Volkswagen Polo GTI         850000
2299                 Toyota Camry Hybrid 2.5        1900000
2323              Audi A4 30 TFSI Technology        3100000
2337               Mercedes-Benz E-Class 230        1000000
2404                Honda City i-VTEC CVT ZX        1225000
2461                  Maruti Wagon R AMT VXI         300000
2531                 Maruti Alto K10 VXI AGS         375000
2859                   Maruti Celerio ZXI AT         509999
3045                    Maruti Swift AMT VXI         575000
3157                  Maruti Wagon R AMT VXI         300000
3356  Hyundai Elite i20 Asta Option CVT BSIV         635000
3537         Maruti Ignis 1.2 AMT Alpha BSIV         700000
3655            Maruti Baleno Zeta Automatic         700000
3730   Hyundai Grand i10 1.2 Kappa Sportz AT         550000
3846                 Datsun RediGO AMT 1.0 S         300000
3860          Hyundai Creta 1.6 SX Automatic        1035000
3892              Volkswagen Polo GT 1.0 TSI         950000
4119           Honda Amaze V CVT Petrol BSIV         725000
4311                 Toyota Camry Hybrid 2.5        1900000

In [ ]:
'''
Data Types
-----------------------------------------------------------------------------------------------------------
same as python(int,str,bool,none,complex,float)+ DateTime(not in python but in pandas)

Types of Data
------------------------------------------------------------------------------------------------------------
1. Numeric-> Discrete-> Whole numbers(positive/negative) eg. ID Columns
             Continuous-> Whole numbers/decimal numbers(positive/negative) eg. salary, temperature, sales
             
2. Categorical-> Nominal-> Category which can't be compared eg. blood types, gender, colors, etc
                 Ordinal-> Category which can be compared eg. grades, disease stages
'''