# Data Cleaning

In [103]:
'''
1. Handle missing/null values
    a. Fill Null Values
    
    -> .fillna()
     
        -Continuous Data-> Mean, Median
        -Discrete/ Categorical Data-> Mode
    -------------------------------------------------------------------------------------------------------------------------    
    Continuous data
    -------------------------------------------------------------------------------------------------------------------------   
    -> to fill, we first need to find skewness using .skew()
    
    ->skewness 0-0.5-> fill mean value
    -> skewness <0(Negative skewness) or > skewness 0.5(Positive Skewness)-> fill median value
    
    -> or using mean and median value of a column
    
        -> if both mean equal/near equal, fill mean value
        -> if mean median not equal and vast difference, fill median value
   -----------------------------------------------------------------------------------------------------------------------------
    b. Drop Null Values
    ->.dropna()
---------------------------------------------------------------------------------------------------------------------------------   
2. Remove unwanted data
    -> Remove whitespace
        -> .strip(), .lstrip(), .rstrip()
        
    -> Remove Regular Expressions(regex) if needed/ Remove unwanted texts
        -> .replace()
---------------------------------------------------------------------------------------------------------------------------------
3. Change Data types
-> .astype()
--------------------------------------------------------------------------------------------------------------------------------
4. Handling duplicate Records
---------------------------------------------------------------------------------------------------------------------------------
-> Find duplicate records
    -> .duplicated()-> checks entire row wise
    -> .duplicated(subset)-> checks col wise

-> To remove duplicate records
    -> .drop_duplicates()

'''

'\n1. Handle missing/null values\n    a. Fill Null Values\n    \n    -> .fillna()\n     \n        -Continuous Data-> Mean, Median\n        -Discrete/ Categorical Data-> Mode\n    -------------------------------------------------------------------------------------------------------------------------    \n    Continuous data\n    -------------------------------------------------------------------------------------------------------------------------   \n    -> to fill, we first need to find skewness using .skew()\n    \n    ->skewness 0-0.5-> fill mean value\n    -> skewness <0(Negative skewness) or > skewness 0.5(Positive Skewness)-> fill median value\n    \n    -> or using mean and median value of a column\n    \n        -> if both mean equal/near equal, fill mean value\n        -> if mean median not equal and vast difference, fill median value\n   -----------------------------------------------------------------------------------------------------------------------------\n    b. Drop Null Values\n    ->.dropna()\n---------------------------------------------------------------------------------------------------------------------------------   \n2. Remove unwanted data\n    -> Remove whitespace\n        -> .strip(), .lstrip(), .rstrip()\n        \n    -> Remove Regular Expressions(regex) if needed/ Remove unwanted texts\n        -> .replace()\n---------------------------------------------------------------------------------------------------------------------------------\n3. Change Data types\n-> .astype()\n--------------------------------------------------------------------------------------------------------------------------------\n4. Handling duplicate Records\n---------------------------------------------------------------------------------------------------------------------------------\n-> Find duplicate records\n    -> .duplicated()-> checks entire row wise\n    -> .duplicated(subset)-> checks col wise\n\n-> To remove duplicate records\n    -> .drop_duplicates()\n\n'

In [104]:
import pandas as pd

In [105]:
df = pd.read_csv('D:\Data Science\Dataset\Employees.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Acer\AppData\Local\Temp\ipykernel_3040\2969773937.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv('D:\Data Science\Dataset\Employees.csv')

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [106]:
df.isnull()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,False,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
106,False,False,False,False,False,False,False,False,True,False,False
107,False,False,False,False,False,False,False,False,True,False,False
108,False,False,False,False,False,False,False,False,True,False,False
109,False,False,False,False,False,False,False,False,True,False,False
110,False,False,False,False,False,False,False,False,True,False,False

In [107]:
df.isnull().sum()  #total null values in each col

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [108]:
df.isnull().sum().sum() # total null values in entire dataset

78

In [109]:
df.isna().sum().sum()

78

# Drop Null Values

In [110]:
'''
-dropna(axis=0/1, how='any'/'all', inplace=True/False)

-axis-> 0=row and 1=col

-how-> any->data should have any one null value.
        all-> data should have all null value.
        
-inplace-> True(permanent change to data(not in excel))
            False(temporary change to data)
            
default axis-0 how='any' inplace=False
            
'''

"\n-dropna(axis=0/1, how='any'/'all', inplace=True/False)\n\n-axis-> 0=row and 1=col\n\n-how-> any->data should have any one null value.\n        all-> data should have all null value.\n        \n-inplace-> True(permanent change to data(not in excel))\n            False(temporary change to data)\n            \ndefault axis-0 how='any' inplace=False\n            \n"

In [111]:
# dropna() only removes rowwise , we can use args in dropna() to remove col
# df = df.dropna()
# or
# df.dropna(inplace=True)

In [112]:
df.isna().sum().sum()

78

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [114]:
# drop any col
# df.drop(columns=['COMMISSION_PCT','PHONE_NUMBER'])

In [115]:
# drop any rows
# df.drop(index=[0,1,2,4])

# Handle Duplicate Records

In [116]:
# find duplicates
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
106    False
107     True
108     True
109     True
110     True
Length: 111, dtype: bool

In [117]:
duplicates=df[df.duplicated(subset='EMPLOYEE_ID')]
duplicates

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [118]:
# df.drop_duplicates(subset='EMPLOYEE_ID', keep='last', inplace=True)
# df

# Filling Null Values

In [119]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

## Fill Commission value

In [120]:
commission_mean = round(df['COMMISSION_PCT'].mean(),2)
commission_median = df['COMMISSION_PCT'].median()
commission_skew = df['COMMISSION_PCT'].skew()

In [121]:
print(commission_mean)
print(commission_median)
print(commission_skew)

0.22
0.2
0.09661736135041571

In [122]:
# df['COMMISSION_PCT'].fillna(commission_mean, inplace=True) #this method wont be used in future starting from pandas 3.0
# another method below:

df.fillna({'COMMISSION_PCT':commission_mean}, inplace=True) #using dict best method 

# we have another method as well but in case of spelling mistake it forms a new col
# df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(commission_mean)
# df

## Filling custom records

In [123]:
# df.fillna({'COMMISSION_PCT':0}, inplace=True)
# here custom record is 0

In [124]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.22,205.0,110.0

In [125]:
df.isna().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        1
DEPARTMENT_ID     1
dtype: int64

# Filling Categorical data (Manager and Department Values)

In [126]:
mgr_mode = df['MANAGER_ID'].mode()[0]
dep_mode = df['DEPARTMENT_ID'].mode()[0]

In [127]:
print(mgr_mode)
print('\n')
print(dep_mode)

100.0


50.0

In [128]:
df.fillna({'MANAGER_ID': mgr_mode}, inplace=True)
df.fillna({'DEPARTMENT_ID': dep_mode}, inplace=True)

In [129]:
df.to_csv('cleaned_employee.csv', index=False)

# Removing Unwanted Data

In [130]:
hr = pd.read_csv('D:\Data Science\Dataset\HR_Dataset Refresh.csv')
hr.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Acer\AppData\Local\Temp\ipykernel_3040\2481661502.py:1: SyntaxWarning: invalid escape sequence '\D'
  hr = pd.read_csv('D:\Data Science\Dataset\HR_Dataset Refresh.csv')

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [131]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

In [132]:
hr.isna().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [133]:
hr.fillna({'ManagerID': 39}, inplace=True)

### Find Duplicate record

In [134]:
duplicate_emp = hr[hr.duplicated(subset='EmpID')]
duplicate_emp

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
19,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
20,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
21,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
22,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
23,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [135]:
emp_id = int(input("Enter employee ID: "))
duplicates=hr[hr['EmpID']==emp_id]
duplicates

Empty DataFrame
Columns: [Employee_Name, EmpID, MarriedID, MaritalStatusID, GenderID, EmpStatusID, DeptID, PerfScoreID, FromDiversityJobFairID, Salary, Termd, PositionID, Position, State, Zip, DOB, Gender, MaritalDesc, CitizenDesc, HispanicLatino, RaceDesc, DateofHire, DateofTermination, TermReason, EmploymentStatus, Department, ManagerName, ManagerID, RecruitmentSource, PerformanceScore, EngagementSurvey, EmpSatisfaction, SpecialProjectsCount, LastPerformanceReview_Date, DaysLateLast30, Absences]
Index: []

[0 rows x 36 columns]

### Removing duplicate Records

In [136]:
hr=hr.drop_duplicates(subset='EmpID')

## Remove unwanted values

### Remove whitespaces

In [137]:
# strip(), lstrip(), rstrip()
# removing only for 1 col
hr['Department'] = hr['Department'].str.strip()
hr['Department'].unique()

array(['Production', 'IT/IS', 'Software Engineering', 'Admin Offices',
       'Sales', 'Executive Office'], dtype=object)

In [138]:
# select_dtype()-> extracts col of specific data type only 
# we need to remove whitespae for all col with dtype object
object_columns = hr.select_dtypes('object')
# to extract multiple dtypes pass it in a list eg. hr.select_dtypes(['object', 'float'])
object_columns

,Employee_Name,Position,State,DOB,Gender,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,DateofHire,DateofTermination,TermReason,EmploymentStatus,Department,ManagerName,RecruitmentSource,PerformanceScore,LastPerformanceReview_Date
0,"Adinolfi, Wilson K",Production Technician I,MA,7/10/1983,M,Single,US Citizen,No,White,7/5/2011,NaN,N/A-StillEmployed,Active,Production,Michael Albert,LinkedIn,Exceeds,1/17/2019
1,"Ait Sidi, Karthikeyan",Sr. DBA,MA,5/5/1975,M,Married,US Citizen,No,White,3/30/2015,6/16/2016,career change,Voluntarily Terminated,IT/IS,Simon Roup,Indeed,Fully Meets,2/24/2016
2,"Akinkuolie, Sarah",Production Technician II,MA,9/19/1988,F,Married,US Citizen,No,White,7/5/2011,9/24/2012,hours,Voluntarily Terminated,Production,Kissy Sullivan,LinkedIn,Fully Meets,5/15/2012
3,"Alagbe,Trina",Production Technician I,MA,9/27/1988,F,Married,US Citizen,No,White,1/7/2008,NaN,N/A-StillEmployed,Active,Production,Elijiah Gray,Indeed,Fully Meets,1/3/2019
4,"Anderson, Carol",Production Technician I,MA,9/8/1989,F,Divorced,US Citizen,No,White,7/11/2011,9/6/2016,return to school,Voluntarily Terminated,Production,Webster Butler,Google Search,Fully Meets,2/1/2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",Production Technician II,MA,5/11/1985,M,Single,US Citizen,No,White,7/7/2014,NaN,N/A-StillEmployed,Active,Production,Kissy Sullivan,LinkedIn,Fully Meets,2/28/2019
326,"Ybarra, Catherine",Production Technician I,MA,5/4/1982,F,Single,US Citizen,No,Asian,9/2/2008,9/29/2015,Another position,Voluntarily Terminated,Production,Brannon Miller,Google Search,PIP,9/2/2015
327,"Zamora, Jennifer",CIO,MA,8/30/1979,F,Single,US Citizen,No,White,4/10/2010,NaN,N/A-StillEmployed,Active,IT/IS,Janet King,Employee Referral,Exceeds,2/21/2019
328,"Zhou, Julia",Data Analyst,MA,2/24/1979,F,Single,US Citizen,No,White,3/30/2015,NaN,N/A-StillEmployed,Active,IT/IS,Simon Roup,Employee Referral,Fully Meets,2/1/2019
329,"Zima, Colleen",Production Technician I,MA,8/17/1978,F,Widowed,US Citizen,No,Asian,9/29/2014,NaN,N/A-StillEmployed,Active,Production,David Stanley,LinkedIn,Fully Meets,1/30/2019

In [139]:
object_columns = object_columns.drop(columns=['DOB','DateofHire','DateofTermination','LastPerformanceReview_Date'])
object_columns

,Employee_Name,Position,State,Gender,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,TermReason,EmploymentStatus,Department,ManagerName,RecruitmentSource,PerformanceScore
0,"Adinolfi, Wilson K",Production Technician I,MA,M,Single,US Citizen,No,White,N/A-StillEmployed,Active,Production,Michael Albert,LinkedIn,Exceeds
1,"Ait Sidi, Karthikeyan",Sr. DBA,MA,M,Married,US Citizen,No,White,career change,Voluntarily Terminated,IT/IS,Simon Roup,Indeed,Fully Meets
2,"Akinkuolie, Sarah",Production Technician II,MA,F,Married,US Citizen,No,White,hours,Voluntarily Terminated,Production,Kissy Sullivan,LinkedIn,Fully Meets
3,"Alagbe,Trina",Production Technician I,MA,F,Married,US Citizen,No,White,N/A-StillEmployed,Active,Production,Elijiah Gray,Indeed,Fully Meets
4,"Anderson, Carol",Production Technician I,MA,F,Divorced,US Citizen,No,White,return to school,Voluntarily Terminated,Production,Webster Butler,Google Search,Fully Meets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",Production Technician II,MA,M,Single,US Citizen,No,White,N/A-StillEmployed,Active,Production,Kissy Sullivan,LinkedIn,Fully Meets
326,"Ybarra, Catherine",Production Technician I,MA,F,Single,US Citizen,No,Asian,Another position,Voluntarily Terminated,Production,Brannon Miller,Google Search,PIP
327,"Zamora, Jennifer",CIO,MA,F,Single,US Citizen,No,White,N/A-StillEmployed,Active,IT/IS,Janet King,Employee Referral,Exceeds
328,"Zhou, Julia",Data Analyst,MA,F,Single,US Citizen,No,White,N/A-StillEmployed,Active,IT/IS,Simon Roup,Employee Referral,Fully Meets
329,"Zima, Colleen",Production Technician I,MA,F,Widowed,US Citizen,No,Asian,N/A-StillEmployed,Active,Production,David Stanley,LinkedIn,Fully Meets

In [140]:
object_columns.columns

Index(['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore'],
      dtype='object')

In [141]:
columns = ['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore']
for col in columns:
    print(col)
    unique_values = hr[col].unique()
    print(unique_values)
    print('\n')

Employee_Name
['Adinolfi, Wilson  K' 'Ait Sidi, Karthikeyan   ' 'Akinkuolie, Sarah'
 'Alagbe,Trina' 'Anderson, Carol ' 'Anderson, Linda  ' 'Andreola, Colby'
 'Athwal, Sam' 'Bachiochi, Linda' 'Bacong, Alejandro '
 'Baczenski, Rachael  ' 'Barbara, Thomas' 'Barbossa, Hector'
 'Barone, Francesco  A' 'Barton, Nader' 'Bates, Norman' 'Beak, Kimberly  '
 'Beatrice, Courtney ' 'Becker, Renee' 'Becker, Scott' 'Bernstein, Sean'
 'Biden, Lowan  M' 'Billis, Helen' 'Blount, Dianna' 'Bondwell, Betsy'
 'Booth, Frank' 'Boutwell, Bonalyn' 'Bozzi, Charles' 'Brill, Donna'
 'Brown, Mia' 'Buccheri, Joseph  ' 'Bugali, Josephine ' 'Bunbury, Jessica'
 'Burke, Joelle' 'Burkett, Benjamin ' 'Cady, Max ' 'Candie, Calvin'
 'Carabbio, Judith' 'Carey, Michael  ' 'Carr, Claudia  N'
 'Carter, Michelle ' 'Chace, Beatrice ' 'Champaigne, Brian' 'Chan, Lin'
 'Chang, Donovan  E' 'Chigurh, Anton' 'Chivukula, Enola'
 'Cierpiszewski, Caroline  ' 'Clayton, Rick' 'Cloninger, Jennifer'
 'Close, Phil' 'Clukey, Elijian' 'Cockel, James' 'Cole, Spencer'
 'Corleone, Michael' 'Corleone, Vito' 'Cornett, Lisa ' 'Costello, Frank'
 'Crimmings,   Jean' 'Cross, Noah' 'Daneault, Lynn' 'Daniele, Ann  '
 "Darson, Jene'ya " 'Davis, Daniel' 'Dee, Randy' 'DeGweck,  James'
 'Del Bosque, Keyla' 'Delarge, Alex' 'Demita, Carla' 'Desimone, Carl '
 'DeVito, Tommy' 'Dickinson, Geoff ' 'Dietrich, Jenna  ' 'DiNocco, Lily '
 'Dobrin, Denisa  S' 'Dolan, Linda' 'Dougall, Eric' 'Driver, Elle'
 'Dunn, Amy  ' 'Dunne, Amy' 'Eaton, Marianne' 'Engdahl, Jean'
 'England, Rex' 'Erilus, Angela' 'Estremera, Miguel' 'Evensen, April'
 'Exantus, Susan' 'Faller, Megan ' 'Fancett, Nicole' 'Ferguson, Susan'
 'Fernandes, Nilson  ' 'Fett, Boba' 'Fidelia,  Libby'
 'Fitzpatrick, Michael  J' 'Foreman, Tanya' 'Forrest, Alex' 'Foss, Jason'
 'Foster-Baker, Amy' 'Fraval, Maruk ' 'Galia, Lisa' 'Garcia, Raul'
 'Gaul, Barbara' 'Gentry, Mildred' 'Gerke, Melisa' 'Gill, Whitney  '
 'Gilles, Alex' 'Girifalco, Evelyn' 'Givens, Myriam' 'Goble, Taisha'
 'Goeth, Amon' 'Gold, Shenice  ' 'Gonzalez, Cayo' 'Gonzalez, Juan'
 'Gonzalez, Maria' 'Good, Susan' 'Gordon, David' 'Gosciminski, Phylicia  '
 'Goyal, Roxana' 'Gray, Elijiah  ' 'Gross, Paula' 'Gruber, Hans'
 'Guilianno, Mike' 'Handschiegl, Joanne' 'Hankard, Earnest'
 'Harrington, Christie ' 'Harrison, Kara' 'Heitzman, Anthony'
 'Hendrickson, Trina' 'Hitchcock, Alfred' 'Homberger, Adrienne  J'
 'Horton, Jayne' 'Houlihan, Debra' 'Howard, Estelle' 'Hudson, Jane'
 'Hunts, Julissa' 'Hutter, Rosalie' 'Huynh, Ming' 'Immediato, Walter'
 'Ivey, Rose ' 'Jackson, Maryellen' 'Jacobi, Hannah  ' 'Jeannite, Tayana'
 'Jhaveri, Sneha  ' 'Johnson, George' 'Johnson, Noelle ' 'Johnston, Yen'
 'Jung, Judy  ' 'Kampew, Donysha' 'Keatts, Kramer '
 'Khemmich, Bartholemew' 'King, Janet' 'Kinsella, Kathleen  '
 'Kirill, Alexandra  ' 'Knapp, Bradley  J' 'Kretschmer, John'
 'Kreuger, Freddy' 'Lajiri,  Jyoti' 'Landa, Hans' 'Langford, Lindsey'
 'Langton, Enrico' 'LaRotonda, William  ' 'Latif, Mohammed' 'Le, Binh'
 'Leach, Dallas' 'LeBlanc, Brandon  R' 'Lecter, Hannibal'
 'Leruth, Giovanni' 'Liebig, Ketsia' 'Linares, Marilyn ' 'Linden, Mathew'
 'Lindsay, Leonara ' 'Lundy, Susan' 'Lunquist, Lisa' 'Lydon, Allison'
 'Lynch, Lindsay' 'MacLennan, Samuel' 'Mahoney, Lauren  '
 'Manchester, Robyn' 'Mancuso, Karen' 'Mangal, Debbie' 'Martin, Sandra'
 'Maurice, Shana' "Carthy, B'rigit" 'Mckenna, Sandy' 'McKinzie, Jac'
 'Meads, Elizabeth' 'Medeiros, Jennifer' 'Miller, Brannon' 'Miller, Ned'
 'Monkfish, Erasumus' 'Monroe, Peter' 'Monterro, Luisa' 'Moran, Patrick'
 'Morway, Tanya' 'Motlagh,  Dawn' 'Moumanil, Maliki ' 'Myers, Michael'
 'Navathe, Kurt' 'Ndzi, Colombui' 'Ndzi, Horia' 'Newman, Richard '
 'Ngodup, Shari ' 'Nguyen, Dheepa' 'Nguyen, Lei-Ming' 'Nowlan, Kristie'
 "O'hare, Lynn" 'Oliver, Brooke ' 'Onque, Jasmine' 'Osturnka, Adeel'
 'Owad, Clinton' 'Ozark, Travis' 'Panjwani, Nina' 'Patronick, Lucas'
 'Pearson, Randall' 'Smith, Martin' 'Pelletier, Ermine' 'Perry, Shakira'
 'Peters, Lauren' 'Peterson, Ebonee  ' 'Petingill, Shana  '
 'Petrowsky, Thelma' 'Pham, Hong' 'Pitt, Brad ' 'Potts, Xana'
 'Power, Morissa' 'Punjabhi, Louis  ' 'Purinton, Janine' 'Quinn, Sean'
 'Rachael, Maggie' 'Rarrick, Quinn' 'Ren, Kylo' 'Rhoads, Thomas'
 'Rivera, Haley  ' 'Roberson, May' 'Robertson, Peter' 'Robinson, Alain  '
 'Robinson, Cherly' 'Robinson, Elias' 'Roby, Lori ' 'Roehrich, Bianca'
 'Roper, Katie' 'Rose, Ashley  ' 'Rossetti, Bruno' 'Roup,Simon'
 'Ruiz, Ricardo' 'Saada, Adell' 'Saar-Beckles, Melinda' 'Sadki, Nore  '
 'Sahoo, Adil' 'Salter, Jason' 'Sander, Kamrin' 'Sewkumar, Nori'
 'Shepard, Anita ' 'Shields, Seffi' 'Simard, Kramer' 'Singh, Nan '
 'Sloan, Constance' 'Smith, Joe' 'Smith, John' 'Smith, Leigh Ann'
 'Smith, Sade' 'Soto, Julia ' 'Soze, Keyser' 'Sparks, Taylor  '
 'Spirea, Kelley' 'Squatrito, Kristen' 'Stanford,Barbara  M'
 'Stansfield, Norman' 'Steans, Tyrone  ' 'Stoica, Rick' 'Strong, Caitrin'
 'Sullivan, Kissy ' 'Sullivan, Timothy' 'Sutwell, Barbara' 'Szabo, Andrew'
 'Tannen, Biff' 'Tavares, Desiree  ' 'Tejeda, Lenora ' 'Terry, Sharlene '
 'Theamstern, Sophia' 'Thibaud, Kenneth' 'Tippett, Jeanette'
 'Torrence, Jack' 'Trang, Mei' 'Tredinnick, Neville ' 'True, Edward'
 'Trzeciak, Cybil' 'Turpin, Jumil' 'Valentin,Jackie' 'Veera, Abdellah '
 'Vega, Vincent' 'Villanueva, Noah' 'Voldemort, Lord' 'Volk, Colleen'
 'Von Massenbach, Anna' 'Walker, Roger' 'Wallace, Courtney  E'
 'Wallace, Theresa' 'Wang, Charlie' 'Warfield, Sarah' 'Whittier, Scott'
 'Wilber, Barry' 'Wilkes, Annie' 'Williams, Jacquelyn  '
 'Winthrop, Jordan  ' 'Wolk, Hang  T' 'Woodson, Jason'
 'Ybarra, Catherine ' 'Zamora, Jennifer' 'Zhou, Julia' 'Zima, Colleen']


Position
['Production Technician I' 'Sr. DBA' 'Production Technician II'
 'Software Engineer' 'IT Support' 'Data Analyst' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'BI Director' 'Director of Operations' 'Sr. Network Engineer'
 'Sales Manager' 'BI Developer' 'IT Manager - Support' 'Network Engineer'
 'IT Director' 'Director of Sales' 'Administrative Assistant'
 'President & CEO' 'Senior BI Developer' 'Shared Services Manager'
 'IT Manager - Infra' 'Principal Data Architect' 'Data Architect'
 'IT Manager - DB' 'Data Analyst ' 'CIO']


State
['MA' 'TX' 'CT' 'VA' 'VT' 'AL' 'WA' 'CA' 'OH' 'IN' 'TN' 'NH' 'RI' 'PA'
 'CO' 'NY' 'UT' 'GA' 'FL' 'NC' 'KY' 'ID' 'NV' 'MT' 'OR' 'ND' 'AZ' 'ME']


Gender
['M ' 'F']


MaritalDesc
['Single' 'Married' 'Divorced' 'Widowed' 'Separated']


CitizenDesc
['US Citizen' 'Eligible NonCitizen' 'Non-Citizen']


HispanicLatino
['No' 'Yes' 'no' 'yes']


RaceDesc
['White' 'Black or African American' 'Two or more races' 'Asian'
 'American Indian or Alaska Native' 'Hispanic']


TermReason
['N/A-StillEmployed' 'career change' 'hours' 'return to school'
 'Another position' 'unhappy' 'attendance' 'performance'
 'Learned that he is a gangster' 'retiring' 'relocation out of area'
 'more money' 'military' 'no-call, no-show' 'Fatal attraction'
 'maternity leave - did not return' 'medical issues' 'gross misconduct']


EmploymentStatus
['Active' 'Voluntarily Terminated' 'Terminated for Cause']


Department
['Production' 'IT/IS' 'Software Engineering' 'Admin Offices' 'Sales'
 'Executive Office']


ManagerName
['Michael Albert' 'Simon Roup' 'Kissy Sullivan' 'Elijiah Gray'
 'Webster Butler' 'Amy Dunn' 'Alex Sweetwater' 'Ketsia Liebig'
 'Brannon Miller' 'Peter Monroe' 'David Stanley' 'Kelley Spirea'
 'Brandon R. LeBlanc' 'Janet King' 'John Smith' 'Jennifer Zamora'
 'Lynn Daneault' 'Eric Dougall' 'Debra Houlihan' 'Brian Champaigne'
 'Board of Directors']


RecruitmentSource
['LinkedIn' 'Indeed' 'Google Search' 'Employee Referral'
 'Diversity Job Fair' 'On-line Web application' 'CareerBuilder' 'Website'
 'Other']


PerformanceScore
['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']

## Removing whitespace for multiple col

In [142]:
def removeWhitespace(dataframe, columns):
    for col in columns:
        dataframe[col] = dataframe[col].str.strip()
    print('White spaces removed.')

In [143]:
removeWhitespace(hr, columns)

White spaces removed.

## Replace unwanted text, regex from data

In [144]:
'''
str.replace(find, replace_value)

-> for text /char/digits
    -str.replace(find, replace_value)
-> for special characters
    -str.replace(find, replace_value, regex=False/True(default true))
    
'''

'\nstr.replace(find, replace_value)\n\n-> for text /char/digits\n    -str.replace(find, replace_value)\n-> for special characters\n    -str.replace(find, replace_value, regex=False/True(default true))\n    \n'

In [145]:
hr['HispanicLatino'] = hr['HispanicLatino'].str.capitalize()

In [146]:
hr['HispanicLatino'].unique()

array(['No', 'Yes'], dtype=object)

In [147]:
hr['Employee_Name'] = hr['Employee_Name'].str.replace(',', '', regex= False)

## Data type Conversion

In [148]:
# astype(datatype)-> only used for data type used in python conversion
hr['ManagerID'] = hr['ManagerID'].astype(int)

In [149]:
'''
-pandas function -> pd.to_datetime(column, format/dayfirst)
-after conversion -> YYYY-MM-DD
----------------------------------------------------------------------------
Format
-%d.%m.%y
-%d-%m-%y
-mixed

dayfirst=True/False(default)
'''

'\n-pandas function -> pd.to_datetime(column, format/dayfirst)\n-after conversion -> YYYY-MM-DD\n----------------------------------------------------------------------------\nFormat\n-%d.%m.%y\n-%d-%m-%y\n-mixed\n\ndayfirst=True/False(default)\n'

In [150]:
date_columns = ['DOB','DateofHire','DateofTermination','LastPerformanceReview_Date']
hr['DOB'] = pd.to_datetime(hr['DOB'])

### Function to convert datetime

In [151]:
def dateConverter(dataframe, *args):
    for col in args:
        hr[col]=pd.to_datetime(hr[col], format='mixed')
    print('Datetime converted.')

In [152]:
dateConverter(hr,'DOB','DateofHire','DateofTermination','LastPerformanceReview_Date' )

Datetime converted.

In [153]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20,LinkedIn,Fully Meets,4.07,4,0,2019-02-28,0,13
326,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12,Google Search,PIP,3.20,2,0,2015-09-02,5,4
327,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,Janet King,2,Employee Referral,Exceeds,4.60,5,6,2019-02-21,0,16
328,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4,Employee Referral,Fully Meets,5.00,3,5,2019-02-01,0,11
329,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,David Stanley,14,LinkedIn,Fully Meets,4.50,5,0,2019-01-30,0,2

In [154]:
hr.to_csv('cleaned_hr.csv', index=False)
hr.to_excel('cleaned_hr.xlsx', index=False)