In [2]:
import pandas as pd

In [3]:
''' 

- group by
- sort by
- rename
- rename_axis
- to_markdown
- map

-aggregate functions -> sum, count, mean, max, min, nunique(count of unique numbers)

dataframe.groupby('col_name') #for single col groupby
dataframe.groupby([list of col to group])[col_name for aggregation].agg_function()

'''

" \n\n- group by\n- sort by\n- rename\n- rename_axis\n- to_markdown\n- map\n\n-aggregate functions -> sum, count, mean, max, min, nunique(count of unique numbers)\n\ndataframe.groupby('col_name') #for single col groupby\ndataframe.groupby([list of col to group])[col_name for aggregation].agg_function()\n\n"

In [4]:
df = pd.read_csv('cleaned_hr.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,NaN,Anderson

### Find each employee by each employment status

In [5]:
df.groupby('EmploymentStatus')['EmpID'].count()

EmploymentStatus
Active                    207
Terminated for Cause       16
Voluntarily Terminated     88
Name: EmpID, dtype: int64

In [6]:
status_employees = df.groupby('EmploymentStatus')['EmpID'].count()
status_employees

EmploymentStatus
Active                    207
Terminated for Cause       16
Voluntarily Terminated     88
Name: EmpID, dtype: int64

In [7]:
status_employees = df.groupby('EmploymentStatus')['EmpID'].count().reset_index()
status_employees

         EmploymentStatus  EmpID
0                  Active    207
1    Terminated for Cause     16
2  Voluntarily Terminated     88

In [8]:
status_employees = df.groupby('EmploymentStatus')['EmpID'].count().reset_index().rename(
    columns={'EmpID':'Total Employees', 'EmploymentStatus':'Employment Status'}
)
status_employees

        Employment Status  Total Employees
0                  Active              207
1    Terminated for Cause               16
2  Voluntarily Terminated               88

In [9]:
status_employees = df.groupby('EmploymentStatus')['EmpID'].count().rename('Total Employees').rename_axis('Employment Status').to_markdown()
print(status_employees)

| Employment Status      |   Total Employees |
|:-----------------------|------------------:|
| Active                 |               207 |
| Terminated for Cause   |                16 |
| Voluntarily Terminated |                88 |

In [10]:
status_employees = df.groupby('EmploymentStatus')['EmpID'].count().rename('Total Employees').rename_axis('Employment Status').to_markdown(numalign = 'center', stralign = 'center')
print(status_employees)

|   Employment Status    |  Total Employees  |
|:----------------------:|:-----------------:|
|         Active         |        207        |
|  Terminated for Cause  |        16         |
| Voluntarily Terminated |        88         |

### Find total employees by each Employment Staus and Gender.

In [11]:
emp_gender_count = df.groupby(['EmploymentStatus','Gender'])['EmpID'].count().reset_index()
emp_gender_count

         EmploymentStatus Gender  EmpID
0                  Active      F    116
1                  Active      M     91
2    Terminated for Cause      F      9
3    Terminated for Cause      M      7
4  Voluntarily Terminated      F     51
5  Voluntarily Terminated      M     37

In [12]:
emp_gender_count = df.groupby(['EmploymentStatus','Gender'])['EmpID'].count().reset_index().rename(
    columns={'EmpID':'Total Employees', 'EmploymentStatus':'Employment Status'})
emp_gender_count

        Employment Status Gender  Total Employees
0                  Active      F              116
1                  Active      M               91
2    Terminated for Cause      F                9
3    Terminated for Cause      M                7
4  Voluntarily Terminated      F               51
5  Voluntarily Terminated      M               37

## Find total salary distributed and total employees in each department.

In [13]:
emp_sal = df.groupby('Department').agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary','sum')
).reset_index()
emp_sal

             Department  Total_Employees  Total_Salary
0         Admin Offices                9        646127
1      Executive Office                1        250000
2                 IT/IS               50       4853232
3            Production              209      12530291
4                 Sales               31       2140899
5  Software Engineering               11       1044884

In [14]:
emp_sal = df.groupby('Department').agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary','sum')
).reset_index().rename(
    columns={'Total_Employees':'Total Employees'} # to replace col.
)
emp_sal

             Department  Total Employees  Total_Salary
0         Admin Offices                9        646127
1      Executive Office                1        250000
2                 IT/IS               50       4853232
3            Production              209      12530291
4                 Sales               31       2140899
5  Software Engineering               11       1044884

In [15]:
emp_sal = df.groupby('Department').agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary','sum')
).reset_index()
emp_sal.columns = emp_sal.columns.str.replace('_',' ',regex=False) #here we can change col name by replacing '_' by' '
emp_sal

             Department  Total Employees  Total Salary
0         Admin Offices                9        646127
1      Executive Office                1        250000
2                 IT/IS               50       4853232
3            Production              209      12530291
4                 Sales               31       2140899
5  Software Engineering               11       1044884

In [16]:
emp_sal = df.groupby('Department').agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary','sum')
).reset_index().sort_values(ascending = True, by='Total_Salary', ignore_index = True)
emp_sal.columns = emp_sal.columns.str.replace('_',' ',regex=False) 
emp_sal

             Department  Total Employees  Total Salary
0      Executive Office                1        250000
1         Admin Offices                9        646127
2  Software Engineering               11       1044884
3                 Sales               31       2140899
4                 IT/IS               50       4853232
5            Production              209      12530291

In [17]:
emp_sal = df.groupby('Department').agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary','sum')
).reset_index().sort_values(ascending = True, by='Total_Salary', ignore_index = True)
emp_sal.columns = emp_sal.columns.str.replace('_',' ',regex=False) 
emp_sal['Total Salary'] = emp_sal['Total Salary'].map('Rs{:,.2f}'.format)
emp_sal

             Department  Total Employees     Total Salary
0      Executive Office                1     Rs250,000.00
1         Admin Offices                9     Rs646,127.00
2  Software Engineering               11   Rs1,044,884.00
3                 Sales               31   Rs2,140,899.00
4                 IT/IS               50   Rs4,853,232.00
5            Production              209  Rs12,530,291.00

In [18]:
def currencyConverter(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:.2f}'.format)

In [19]:
emp_sal = df.groupby('Department').agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary','sum'),
    Avg_Salary = ('Salary','mean'),
    Max_Salary = ('Salary','max'),
    Min_Salary = ('Salary','min'),
).reset_index().sort_values(ascending = True, by='Total_Salary', ignore_index = True)
currencyConverter(emp_sal, 'Rs.','Total_Salary','Avg_Salary','Max_Salary','Min_Salary')
emp_sal.columns = emp_sal.columns.str.replace('_',' ',regex=False) 
emp_sal

,Department,Total Employees,Total Salary,Avg Salary,Max Salary,Min Salary
0,Executive Office,1,Rs.250000.00,Rs.250000.00,Rs.250000.00,Rs.250000.00
1,Admin Offices,9,Rs.646127.00,Rs.71791.89,Rs.106367.00,Rs.49920.00
2,Software Engineering,11,Rs.1044884.00,Rs.94989.45,Rs.108987.00,Rs.77692.00
3,Sales,31,Rs.2140899.00,Rs.69061.26,Rs.180000.00,Rs.55875.00
4,IT/IS,50,Rs.4853232.00,Rs.97064.64,Rs.220450.00,Rs.50178.00
5,Production,209,Rs.12530291.00,Rs.59953.55,Rs.170500.00,Rs.45046.00

### Growth %
(current_value-baseline_value)/(baseline_value) *100

### Find the total % of hiring rate of each year

In [20]:
def pctConverter(dataframe, suffix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map('{:.2f}'f'{suffix}'.format)

hire_rate = df.groupby('Hire_Year')['EmpID'].count().reset_index()
hire_rate['Hire%'] = (hire_rate['EmpID'].pct_change().fillna(0))*100
pctConverter(hire_rate,'%','Hire%')
hire_rate

    Hire_Year  EmpID    Hire%
0        2006      1    0.00%
1        2007      2  100.00%
2        2008      3   50.00%
3        2009      7  133.33%
4        2010      9   28.57%
5        2011     83  822.22%
6        2012     45  -45.78%
7        2013     44   -2.22%
8        2014     60   36.36%
9        2015     36  -40.00%
10       2016     14  -61.11%
11       2017      6  -57.14%
12       2018      1  -83.33%

## Total employees hired by each month

In [21]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'Hire_Year', 'Hire_Month', 'Hire_Day', 'Hire_Month_Name',
       'Hire_Day_Name', 'Absence_Label', 'Absence_Id', 'Absence_Label_id',
       'Col1', 'Col2', 'First_Name', 'Middle_Name', 'Last_Name'],
      dtype='object')

In [22]:
month_emp = df.groupby('Hire_Month')['EmpID'].count().reset_index()
month_emp

    Hire_Month  EmpID
0            1     54
1            2     31
2            3     19
3            4     27
4            5     33
5            6      8
6            7     44
7            8     20
8            9     39
9           10      7
10          11     28
11          12      1

In [23]:
month_emp = df.groupby('Hire_Month_Name')['EmpID'].count().reset_index()
month_emp

   Hire_Month_Name  EmpID
0            April     27
1           August     20
2         December      1
3         February     31
4          January     54
5             July     44
6             June      8
7            March     19
8              May     33
9         November     28
10         October      7
11       September     39

In [27]:
month_emp = df.groupby(['Hire_Month','Hire_Month_Name'])['EmpID'].count().reset_index()
month_emp

    Hire_Month Hire_Month_Name  EmpID
0            1         January     54
1            2        February     31
2            3           March     19
3            4           April     27
4            5             May     33
5            6            June      8
6            7            July     44
7            8          August     20
8            9       September     39
9           10         October      7
10          11        November     28
11          12        December      1

In [28]:
month_emp = df.groupby(['Hire_Month','Hire_Month_Name'])['EmpID'].count().reset_index().rename(
    columns={'Hire_Month_Name':'Hire_Month', 'EmpID':'Total_Employees'}
)
month_emp

   Hire_Month Hire_Month  Total_Employees
0           1    January               54
1           2   February               31
2           3      March               19
3           4      April               27
4           5        May               33
5           6       June                8
6           7       July               44
7           8     August               20
8           9  September               39
9          10    October                7
10         11   November               28
11         12   December                1

In [34]:
month_emp = df.groupby(['Hire_Month','Hire_Month_Name'])['EmpID'].count().reset_index().rename(
    columns={'Hire_Month_Name':'Hire_Month', 'EmpID':'Total_Employees'}
)[['Hire_Month', 'Total_Employees']]
month_emp

   Hire_Month Hire_Month  Total_Employees
0           1    January               54
1           2   February               31
2           3      March               19
3           4      April               27
4           5        May               33
5           6       June                8
6           7       July               44
7           8     August               20
8           9  September               39
9          10    October                7
10         11   November               28
11         12   December                1

## Total Employees hired by each day

In [35]:
weekdays = ['Sunday', 'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
df['Hire_Day_Name'] = pd.Categorical(df['Hire_Day_Name'], categories = weekdays)

In [36]:
day_hired = df.groupby(['Hire_Day_Name'], observed=False)['EmpID'].count().reset_index()
day_hired

  Hire_Day_Name  EmpID
0        Sunday      6
1        Monday    259
2       Tuesday     19
3     Wednesday      9
4      Thursday      9
5        Friday      6
6      Saturday      3

In [37]:
# KPI(Key Performance Indicator)
# Summarize data

total_employees = df['EmpID'].count()
total_salary = df['Salary'].sum()
total_managers = df['ManagerID'].nunique()
total_departments = df['Department'].nunique()
total_projects = df['SpecialProjectsCount'].sum()

In [38]:
print(f"Total Employees:{total_employees}")
print(f"Total Salary:Rs.{total_salary}")
print(f"Total Managers:{total_managers}")
print(f"Total Departments:{total_departments}")
print(f"Total Projects:{total_projects}")

Total Employees:311
Total Salary:Rs.21465433
Total Managers:23
Total Departments:6
Total Projects:379