In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cleaned_hr.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,NaN,Anderson

In [3]:
def dateConverter(dataframe, *args):
    for col in args:
        df[col]=pd.to_datetime(df[col], format='mixed')
    print('Datetime converted.')

In [4]:
dateConverter(df,'DOB','DateofHire','DateofTermination','LastPerformanceReview_Date' )

Datetime converted.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    datetime64[ns]
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    datetime64[ns]
 22  DateofTermination           104 non-null    datetime64[ns]
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    int64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    datetime64[ns]
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
 36  Hire_Year                   311 non-null    int64
 37  Hire_Month                  311 non-null    int64
 38  Hire_Day                    311 non-null    int64
 39  Hire_Month_Name             311 non-null    object
 40  Hire_Day_Name               311 non-null    object
 41  Absence_Label               311 non-null    object
 42  Absence_Id                  311 non-null    int64
 43  Absence_Label_id            311 non-null    int64
 44  Col1                        311 non-null    object
 45  Col2                        311 non-null    object
 46  First_Name                  311 non-null    object
 47  Middle_Name                 14 non-null     object
 48  Last_Name                   311 non-null    object
dtypes: datetime64[ns](4), float64(1), int64(22), object(22)
memory usage: 119.2+ KB

# Extract Year, Month , Day

In [6]:
# df['DateofHire']
'''
Date Number (i.e. int)
dt.year-> year
dt.month->month
dt.day->day
-------------------------------------------------------------
Date Name (i.e. string)
dt.day_name()
dt.month_name()
'''

'\nDate Number (i.e. int)\ndt.year-> year\ndt.month->month\ndt.day->day\n-------------------------------------------------------------\nDate Name (i.e. string)\ndt.day_name()\ndt.month_name()\n'

In [7]:
df['Hire_Year'] = df['DateofHire'].dt.year
df['Hire_Month'] = df['DateofHire'].dt.month
df['Hire_Day'] = df['DateofHire'].dt.day
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,July,Monday,High Absence,2,2,High,Absence,Jumil,NaN,Turpin
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,September,Tuesday,Low Absence,0,0,Low,Absence,Jackie,NaN,Valentin
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,April,Saturday,High Absence,2,2,High,Absence,Abdellah,NaN,Veera
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,March,Monday,High Absence,2,2,High,Absence,Vincent,NaN,Vega
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,September,Monday,Low Absence,0,0,Low,Absence,Noah,NaN,Villanueva

In [8]:
df['Hire_Month_Name'] = df['DateofHire'].dt.month_name()
df['Hire_Day_Name'] = df['DateofHire'].dt.day_name()
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,July,Monday,High Absence,2,2,High,Absence,Jumil,NaN,Turpin
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,September,Tuesday,Low Absence,0,0,Low,Absence,Jackie,NaN,Valentin
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,April,Saturday,High Absence,2,2,High,Absence,Abdellah,NaN,Veera
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,March,Monday,High Absence,2,2,High,Absence,Vincent,NaN,Vega
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,September,Monday,Low Absence,0,0,Low,Absence,Noah,NaN,Villanueva

# Convert Continuous data into Categorical Column

In [9]:
'''
0-5-> Low Absence
6-10-> Medium Absence
10>-> High Absence
'''

'\n0-5-> Low Absence\n6-10-> Medium Absence\n10>-> High Absence\n'

In [10]:
df['Absences'].unique()

array([ 1, 17,  3, 15,  2, 19,  4, 16, 12,  9,  7, 20,  8, 13,  5, 14,  6,
       11, 10, 18], dtype=int64)

In [11]:
def absenceCategory(absence):
    if absence>0 and absence<=5:
        return 'Low Absence'
    elif absence>5 and absence<=10:
        return 'Medium Absence'
    elif absence>10:
        return 'High Absence'
    else:
        return 'Error: Negative Absence'

In [12]:
df['Absence_Label'] = df['Absences'].apply(absenceCategory)

In [13]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,July,Monday,High Absence,2,2,High,Absence,Jumil,NaN,Turpin
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,September,Tuesday,Low Absence,0,0,Low,Absence,Jackie,NaN,Valentin
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,April,Saturday,High Absence,2,2,High,Absence,Abdellah,NaN,Veera
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,March,Monday,High Absence,2,2,High,Absence,Vincent,NaN,Vega
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,September,Monday,Low Absence,0,0,Low,Absence,Noah,NaN,Villanueva

# Data Encoding

## Manual Encoding

In [14]:
data = {
    'Low Absence': 0,
    'Medium Absence': 1,
    'High Absence': 2
}

In [15]:
df['Absence_Id'] = df['Absence_Label'].map(data)

In [16]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,July,Monday,High Absence,2,2,High,Absence,Jumil,NaN,Turpin
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,September,Tuesday,Low Absence,0,0,Low,Absence,Jackie,NaN,Valentin
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,April,Saturday,High Absence,2,2,High,Absence,Abdellah,NaN,Veera
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,March,Monday,High Absence,2,2,High,Absence,Vincent,NaN,Vega
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,September,Monday,Low Absence,0,0,Low,Absence,Noah,NaN,Villanueva

In [17]:
def encodeData(dataframe, col_name, *args):
    encode_data = {}
    for idx, val in enumerate(args):
        encode_data[val] = idx
    dataframe[f'{col_name}_id'] = dataframe[col_name].map(encode_data)
    print(f'{col_name} data encoded.')

In [18]:
encodeData(df, 'Absence_Label','Low Absence', 'Medium Absence', 'High Absence')

Absence_Label data encoded.

### Split

In [19]:
df['Absence_Id'].unique()
# split(find, number_of_columns=index, expand=True/False(default))

array([0, 2, 1], dtype=int64)

In [20]:
df['Absence_Label'].str.split()

0       [Low, Absence]
1      [High, Absence]
2       [Low, Absence]
3      [High, Absence]
4       [Low, Absence]
            ...
306    [High, Absence]
307     [Low, Absence]
308    [High, Absence]
309    [High, Absence]
310     [Low, Absence]
Name: Absence_Label, Length: 311, dtype: object

In [21]:
df['Absence_Label'].str.split(' ', n=1, expand=True)

        0        1
0     Low  Absence
1    High  Absence
2     Low  Absence
3    High  Absence
4     Low  Absence
..    ...      ...
306  High  Absence
307   Low  Absence
308  High  Absence
309  High  Absence
310   Low  Absence

[311 rows x 2 columns]

In [22]:
df[['Col1','Col2']] = df['Absence_Label'].str.split(' ', n=1, expand=True)

In [23]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,NaN,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,NaN,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,July,Monday,High Absence,2,2,High,Absence,Jumil,NaN,Turpin
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,September,Tuesday,Low Absence,0,0,Low,Absence,Jackie,NaN,Valentin
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,April,Saturday,High Absence,2,2,High,Absence,Abdellah,NaN,Veera
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,March,Monday,High Absence,2,2,High,Absence,Vincent,NaN,Vega
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,September,Monday,Low Absence,0,0,Low,Absence,Noah,NaN,Villanueva

In [24]:
hr = pd.read_csv('D:\Data Science\Dataset\HR_Dataset Refresh.csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Acer\AppData\Local\Temp\ipykernel_5240\252839289.py:1: SyntaxWarning: invalid escape sequence '\D'
  hr = pd.read_csv('D:\Data Science\Dataset\HR_Dataset Refresh.csv')

In [ ]:
# remove duplicates
# hr.drop_duplicates(subset = 'EmpID', keep = 'first', )

In [25]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [26]:
first_last = hr['Employee_Name'].str.split(',',n=1,expand=True)
first_last.head()

            0                1
0    Adinolfi        Wilson  K
1    Ait Sidi   Karthikeyan
2  Akinkuolie            Sarah
3      Alagbe            Trina
4    Anderson           Carol

In [27]:
first_middle = first_last[1].str.strip().str.split(' ', n=1, expand=True)
first_middle.head()

             0     1
0       Wilson     K
1  Karthikeyan  None
2        Sarah  None
3        Trina  None
4        Carol  None

In [28]:
df['First_Name'] = first_middle[0]
df['Middle_Name'] = first_middle[1]
df['Last_Name'] = first_last[0]

In [29]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Absence_Label,Absence_Id,Absence_Label_id,Col1,Col2,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,July,Tuesday,Low Absence,0,0,Low,Absence,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,March,Monday,High Absence,2,2,High,Absence,Karthikeyan,None,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,July,Tuesday,Low Absence,0,0,Low,Absence,Sarah,None,Akinkuolie
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,January,Monday,High Absence,2,2,High,Absence,Trina,None,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,July,Monday,Low Absence,0,0,Low,Absence,Carol,None,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,July,Monday,High Absence,2,2,High,Absence,Jumil,None,Turpin
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,September,Tuesday,Low Absence,0,0,Low,Absence,Jackie,None,Valentin
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,April,Saturday,High Absence,2,2,High,Absence,Abdellah,None,Veera
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,March,Monday,High Absence,2,2,High,Absence,Vincent,None,Vega
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,September,Monday,Low Absence,0,0,Low,Absence,Noah,None,Villanueva

In [30]:
df.to_csv('cleaned_hr.csv', index = False)