In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('D:\Data Science\Dataset\pizza_sales.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Acer\AppData\Local\Temp\ipykernel_19440\2592235399.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv('D:\Data Science\Dataset\pizza_sales.csv')

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [28]:
duplicate_data = df[df.duplicated()]
duplicate_data

Empty DataFrame
Columns: [pizza_id, order_id, pizza_name_id, quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name]
Index: []

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 4.5+ MB

In [30]:
def dateConverter(dataframe, *args):
    for col in args:
        dataframe[col]=pd.to_datetime(dataframe[col], format='mixed')
    print('Datetime converted.')

In [31]:
dateConverter(df, 'order_date', 'order_time')

Datetime converted.

In [32]:
df['Order_Day'] = df['order_date'].dt.day_name()
df['Order_Month'] = df['order_date'].dt.month_name()
df['month_num'] = df['order_date'].dt.month
df['Order_Hour'] = df['order_time'].dt.hour

In [33]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,Order_Day,Order_Month,month_num,Order_Hour
0,1,1,hawaiian_m,1,2015-01-01,2026-09-09 11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,Thursday,January,1,11
1,2,2,classic_dlx_m,1,2015-01-01,2026-09-09 11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,Thursday,January,1,11
2,3,2,five_cheese_l,1,2015-01-01,2026-09-09 11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,Thursday,January,1,11
3,4,2,ital_supr_l,1,2015-01-01,2026-09-09 11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,Thursday,January,1,11
4,5,2,mexicana_m,1,2015-01-01,2026-09-09 11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,Thursday,January,1,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,2026-09-09 21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza,Thursday,December,12,21
48616,48617,21348,four_cheese_l,1,2015-12-31,2026-09-09 21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza,Thursday,December,12,21
48617,48618,21348,napolitana_s,1,2015-12-31,2026-09-09 21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza,Thursday,December,12,21
48618,48619,21349,mexicana_l,1,2015-12-31,2026-09-09 22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,Thursday,December,12,22
48619,48620,21350,bbq_ckn_s,1,2015-12-31,2026-09-09 23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza,Thursday,December,12,23

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[ns]
 5   order_time         48620 non-null  datetime64[ns]
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
 12  Order_Day          48620 non-null  object
 13  Order_Month        48620 non-null  object
 14  month_num          48620 non-null  int32
 15  Order_Hour         48620 non-null  int32
dtypes: datetime64[ns](2), float64(2), int32(2), int64(3), object(7)
memory usage: 5.6+ MB

# KPI

In [35]:
total_revenue = df['total_price'].sum()
total_pizza_sold = df['quantity'].sum()
total_orders = df['order_id'].nunique()
average_order_value = total_revenue / total_orders
average_pizza_per_year = total_pizza_sold / total_orders

In [36]:
print(f"Total Revenue: ${total_revenue:,.2f}")
print(f"Total Pizza Sold:{total_pizza_sold} qty")
print(f"Total orders: {total_orders}")
print(f"Average order value: ${average_order_value:,.2f}")
print(f"Average pizza order per day : {average_pizza_per_year:,.2f}")

Total Revenue: $817,860.05
Total Pizza Sold:49574 qty
Total orders: 21350
Average order value: $38.31
Average pizza order per day : 2.32

# Analysis

### Sales by day of week

In [37]:
weekdays = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
df['Order_Day'] = pd.Categorical(df['Order_Day'], categories=weekdays)

In [46]:
def currencyConverter(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:.2f}'.format)
        
def pctConverter(dataframe, suffix , *args):
    for col in args:
        dataframe[col] = dataframe[col].map('{:.2f}'f'{suffix}'.format)

In [39]:
day_sales = df.groupby('Order_Day', observed=False)['total_price'].sum().reset_index().rename(
    columns = {'Order_Day':'Weekdays','total_price':'Total Price'}
)
currencyConverter(day_sales, '$','Total Price')
day_sales

    Weekdays Total Price
0     Sunday  $102116.45
1     Monday  $110471.60
2    Tuesday  $115594.45
3  Wednesday  $116731.20
4   Thursday  $121650.30
5     Friday  $129690.90
6   Saturday  $121605.15

# Hourly Trend

In [40]:
hour_sales = df.groupby('Order_Hour')['total_price'].sum().reset_index().rename(
    columns = {'Order_Hour': 'Order Hour','total_price':'Total Price'}
)
currencyConverter(hour_sales, '$','Total Price')
hour_sales

    Order Hour Total Price
0            9      $83.00
1           10     $303.65
2           11   $44935.80
3           12  $111877.90
4           13  $106065.70
5           14   $59201.40
6           15   $52992.30
7           16   $70055.40
8           17   $86237.45
9           18   $89296.85
10          19   $72628.90
11          20   $58215.40
12          21   $42029.80
13          22   $22815.15
14          23    $1121.35

# Monthly Trends

In [44]:
monthly_sales = df.groupby(['month_num','Order_Month']).agg(
    Total_Price = ('total_price','sum'),
    Total_Orders = ('order_id','nunique')
).reset_index()[['Order_Month','Total_Price','Total_Orders']]

currencyConverter(monthly_sales, '$', 'Total_Price')
monthly_sales.columns = monthly_sales.columns.str.replace('_',' ', regex=False)
monthly_sales

   Order Month Total Price  Total Orders
0      January   $71620.15          1929
1     February   $64419.45          1648
2        March   $71301.40          1864
3        April   $70312.00          1829
4          May   $67648.80          1765
5         June   $68161.45          1771
6         July   $70880.65          1860
7       August   $69497.30          1835
8    September   $63803.70          1638
9      October   $68152.20          1782
10    November   $71004.85          1844
11    December   $61058.10          1585

# Percentage Change by Category

In [47]:
cat_sales_pct = df.groupby('pizza_category')['total_price'].sum().reset_index().rename(
    columns = {'pizza_category':'Pizza Category','total_price':'Total Price'}
)
cat_sales_pct['Sales%']=(cat_sales_pct['Total Price']/total_revenue)*100

currencyConverter(cat_sales_pct, '$','Total Price')
pctConverter(cat_sales_pct, '%','Sales%')

cat_sales_pct

  Pizza Category Total Price  Sales%
0        Chicken  $195919.50  23.96%
1        Classic  $220053.10  26.91%
2        Supreme  $208197.00  25.46%
3         Veggie  $193690.45  23.68%

## % Sales by Pizza Size and Category

In [48]:
size_cat_pct = df.groupby(['pizza_size','pizza_category'])['total_price'].sum().reset_index().rename(
    columns = {'pizza_size':'Pizza Size','pizza_category':'Pizza Category','total_price':'Total Price'}
)
size_cat_pct['Sales%']=(size_cat_pct['Total Price']/total_revenue)*100

currencyConverter(size_cat_pct,'$','Total Price')
pctConverter(size_cat_pct, '%', 'Sales%')
size_cat_pct

   Pizza Size Pizza Category Total Price  Sales%
0           L        Chicken  $102339.00  12.51%
1           L        Classic   $74518.50   9.11%
2           L        Supreme   $94258.50  11.53%
3           L         Veggie  $104202.70  12.74%
4           M        Chicken   $65224.50   7.98%
5           M        Classic   $60581.75   7.41%
6           M        Supreme   $66475.00   8.13%
7           M         Veggie   $57101.00   6.98%
8           S        Chicken   $28356.00   3.47%
9           S        Classic   $69870.25   8.54%
10          S        Supreme   $47463.50   5.80%
11          S         Veggie   $32386.75   3.96%
12         XL        Classic   $14076.00   1.72%
13        XXL        Classic    $1006.60   0.12%

In [49]:
size_cat_pct = size_cat_pct.sort_values(ascending=True, by = 'Sales%')
size_cat_pct

   Pizza Size Pizza Category Total Price  Sales%
13        XXL        Classic    $1006.60   0.12%
12         XL        Classic   $14076.00   1.72%
2           L        Supreme   $94258.50  11.53%
0           L        Chicken  $102339.00  12.51%
3           L         Veggie  $104202.70  12.74%
8           S        Chicken   $28356.00   3.47%
11          S         Veggie   $32386.75   3.96%
10          S        Supreme   $47463.50   5.80%
7           M         Veggie   $57101.00   6.98%
5           M        Classic   $60581.75   7.41%
4           M        Chicken   $65224.50   7.98%
6           M        Supreme   $66475.00   8.13%
9           S        Classic   $69870.25   8.54%
1           L        Classic   $74518.50   9.11%

# Total Pizza Sold by Pizza Category

In [51]:
total_pizza = df.groupby('pizza_category')['quantity'].sum().reset_index().rename(
    columns = {'pizza_category':'Pizza Category','quantity':'Quantity'}
).sort_values(ascending=False, by='Quantity',ignore_index=True)
total_pizza

  Pizza Category  Quantity
0        Classic     14888
1        Supreme     11987
2         Veggie     11649
3        Chicken     11050

# Top 5 best selling pizzas

In [53]:
top_5 = df.groupby('pizza_name').agg(
    Total_Revenue = ('total_price','sum'),
    Total_Orders = ('order_id','nunique'),
    Total_Quantity = ('quantity','sum')
).reset_index().rename(
    columns = {'pizza_name':'Pizza Name'}
).sort_values(ascending=False, by='Total_Revenue',ignore_index=True).head()

currencyConverter(top_5, '$','Total_Revenue')
top_5.columns = top_5.columns.str.replace('_',' ', regex=False)
top_5

                     Pizza Name Total Revenue  Total Orders  Total Quantity
0        The Thai Chicken Pizza     $43434.25          2225            2371
1    The Barbecue Chicken Pizza     $42768.00          2273            2432
2  The California Chicken Pizza     $41409.50          2197            2370
3      The Classic Deluxe Pizza     $38180.50          2329            2453
4       The Spicy Italian Pizza     $34831.25          1822            1924

# Bottom 5 least selling pizza

In [54]:
bottom_5 = df.groupby('pizza_name').agg(
    Total_Revenue = ('total_price','sum'),
    Total_Orders = ('order_id','nunique'),
    Total_Quantity = ('quantity','sum')
).reset_index().rename(
    columns = {'pizza_name':'Pizza Name'}
).sort_values(ascending=True, by='Total_Revenue',ignore_index=True).head()

currencyConverter(bottom_5, '$','Total_Revenue')
bottom_5.columns = bottom_5.columns.str.replace('_',' ', regex=False)
bottom_5

                  Pizza Name Total Revenue  Total Orders  Total Quantity
0       The Brie Carre Pizza     $11588.50           480             490
1     The Green Garden Pizza     $13955.75           976             997
2  The Spinach Supreme Pizza     $15277.75           918             950
3    The Mediterranean Pizza     $15360.50           912             934
4    The Spinach Pesto Pizza     $15596.00           945             970